### ISSUE TITLE
Update Code to Reflect Style Guide

### ISSUE THREAD

**Issue by Kfeavel** [panix-os-dev-team/Panix#287]
Areas of Concern:

- [ ] Namespaces (`CamelCase`)
- [ ] Variable naming (`lowerCamelCase`)
- [ ] Functions that should be static
- [ ] Missing function prototypes
- [ ] Single-line while loops should use `continue` (i.e. `while (bool) continue;`)
    - Add `AllowShortLoopsOnASingleLine: true` to `.clang-format`
- [ ] Visit [Clang Format Docs](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) and check for other options to enable

These can be separate pull requests, so format the branch names as `287-code-cleanup-(insert category here)`

**Comment by Kfeavel** [comment]
```yaml
---
Language: Cpp
BasedOnStyle: WebKit

NamespaceIndentation: None
IndentPPDirectives: AfterHash
SpaceAfterTemplateKeyword: false
BraceWrapping:
    AfterFunction: true

BreakBeforeInheritanceComma: true
BreakConstructorInitializers: BeforeComma
BreakBeforeBraces: Custom

AllowShortBlocksOnASingleLine: Always

AlignConsecutiveAssignments: AcrossComments
AlignConsecutiveBitFields: AcrossEmptyLinesAndComments
AlignConsecutiveMacros: AcrossComments
AlignTrailingComments: true
AlignEscapedNewlines: Left
AlignOperands: AlignAfterOperator

```
